languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "LochNAS"
logo = "img/icon.png"
description = "Docker configuration for all-in-one nas setup"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "January 2 2006"

[author]
  name = "LochNAS"
  image = "img/icon.png"
  headline = "Docker configuration for all-in-one nas setup "
  bio = "Docker configuration for all-in-one nas setup "
  links = [
    { github = "https://github.com/SiloCityLabs/lochnas" },
    { telegram = "https://t.me/+Ll8Sx8bn_qJhMjUx" },
    { reddit = "https://www.reddit.com/r/LochNAS" },
    { patreon = "https://patreon.com/silocitylabs" },
    { paypal = "https://paypal.me/ldrrp" },
  ]
